#ifndef VOXELCRAFT_GAME_RUNTIME_H
#define VOXELCRAFT_GAME_RUNTIME_H

#include "core/debug_control.h"
#include "core/debug_dsl.h"
#include "presentation/environment_runtime.h"
#include "app/game_settings.h"
#include "app/game_stream_audit.h"
#include "app/game_debug_trace.h"
#include "space/planet_profile.h"
#include "gameplay/player.h"
#include "gameplay/ship.h"
#include "world/world_types.h"
#include "ecology/flora_taxa.h"
#include "app/app_types.h"
#include "gameplay/player_types.h"
#include "presentation/ui_types.h"

#include <stdbool.h>
#include <stdint.h>

typedef struct LandingTransition {
  bool active;
  bool committed;
  bool landed;
  bool homeWorldTarget;
  float elapsed;
  float duration;
  float summaryRemaining;
  float targetGravity;
  float targetRadius;
  float startDistance;
  float targetDistance;
  float startYaw;
  float startPitch;
  float targetYaw;
  float targetPitch;
  float atmosphereDensity;
  PlanetAtmosphereType atmosphereType;
  int targetSystemAnchorX;
  int targetSystemAnchorZ;
  int targetPlanetIndex;
  Vector3 targetCenter;
  Vector3 targetVelocity;
  Vector3 outward;
  Vector3 atmosphereStart;
  Vector3 landingPosition;
  char targetName[48];
  char landingPoint[64];
  char environment[96];
  char biosphere[96];
} LandingTransition;

typedef struct GameRuntime {
  GameSettings settings;
  Player player;
  Camera3D camera;
  EnvironmentPresentationRuntime environment;
  DebugControl debugControl;
  DebugDslScript *debugDslScript;
  DebugDslExecutor *debugDslExecutor;
  DebugDslEnvironment *debugDslEnvironment;
  PlayerInput scriptedPlayerInput;
  PlayerInput appliedPlayerInput;
  ShipControlInput scriptedShipInput;
  BlockType hotbar[HOTBAR_SIZE];
  ImportDialog importDialog;
  LandingTransition landingTransition;
  GameStreamAuditState streamAudit;
  GameDebugTraceState debugTrace;
  Vector3 blockGalleryOrigin;
  Vector3 floraGalleryOrigin;

  GameScreen screen;
  TerrainMode selectedTerrain;
  uint32_t selectedSeed;
  unsigned scriptedInputFrames;
  unsigned scriptedShipInputFrames;
  uint64_t debugFrame;
  uint64_t debugLeftPressFrame;
  uint64_t debugLeftHandleFrame;
  uint64_t debugLeftSetBlockFrame;
  uint64_t debugLeftMeshFrame;
  unsigned blockGalleryPlaced;
  unsigned floraGalleryPlaced;
  unsigned floraGalleryTreeCount;
  unsigned floraGalleryGroundCount;
  FloraTaxonId floraSampleTree;
  FloraTaxonId floraSampleGround;
  FloraDisturbanceStage floraSampleBurnStage;
  FloraHabitat floraSampleHabitat;
  float scriptedShipInputFrameCarry;

  int selectedIndex;
  int biologyAtlasSlot;
  uint32_t evolutionLockedOrganismId;
  int screenWidth;
  int screenHeight;
  int floraSampleX;
  int floraSampleZ;
  int debugLeftTargetX;
  int debugLeftTargetY;
  int debugLeftTargetZ;
  int chunkWorkerCount;

  bool perfMode;
  bool debugControlEnabled;
  bool debugStdinEnabled;
  bool debugScriptEnabled;
  bool debugScriptPathInvalid;
  bool debugDslBatch;
  bool debugDslFromStdin;
  bool debugDslStartRequested;
  bool debugCommandFailed;
  bool debugStreamWaitFailed;
  bool debugTraceEnabled;
  bool debugTracePathInvalid;
  bool debugResolutionInvalid;
  bool chunkWorkerCountInvalid;
  bool blockGalleryActive;
  bool floraGalleryActive;
  bool floraSampleActive;
  bool showHelp;
  bool showDebug;
  bool scannerActive;
  bool shipLocatorEnabled;
  bool showOrbitTrajectories;
  bool screenshotPending;
  bool quitRequested;
  bool cursorReleased;
  bool paused;
  bool albumOpen;
  bool albumRainSuspended;
  bool wasInSpace;
  bool entitiesWorldActive;
  uint32_t entitiesWorldDimension;
  bool thirdPerson;
  bool scriptedInputFirstFrame;
  bool debugMouseLeftPressed;
  bool debugMouseRightPressed;
  bool debugLeftMeshPending;
  bool autoSaveEnabled;
  bool dayCycleEnabled;
  bool evolutionScanLocked;
  bool biologyAtlasOpen;
  bool quitSaveDone;

  float autoSaveTimer;
  float dayTime;
  int processExitCode;
  bool processExitRequested;
  size_t debugDslInputLength;
  int debugDslBraceDepth;
  char perfReportPath[512];
  char perfBaselinePath[512];
  char debugScriptPath[512];
  char debugCommandFailure[128];
  char debugStreamWaitFailure[128];
  char debugTracePath[512];
  char debugDslInput[16384];
} GameRuntime;

void GameRuntimeInit(GameRuntime *runtime, int argc, char **argv);

#endif
