#ifndef VOXELCRAFT_CONFIG_H
#define VOXELCRAFT_CONFIG_H

#define CHUNK_SIZE 16
#define SURFACE_SECTION_HEIGHT 16
#define SURFACE_MIN_Y (-16384)
#define SURFACE_MAX_Y_EXCLUSIVE 16384
#define SURFACE_COORDINATE_SPAN \
    (SURFACE_MAX_Y_EXCLUSIVE - SURFACE_MIN_Y)
#define SURFACE_SECTION_MIN_Y (SURFACE_MIN_Y / SURFACE_SECTION_HEIGHT)
#define SURFACE_SECTION_MAX_Y_EXCLUSIVE \
    (SURFACE_MAX_Y_EXCLUSIVE / SURFACE_SECTION_HEIGHT)
#define SURFACE_SECTION_COUNT \
    (SURFACE_SECTION_MAX_Y_EXCLUSIVE - SURFACE_SECTION_MIN_Y)

// Existing terrain generation remains in this band while signed coordinate
// support is rolled out independently of the terrain scale model.
#define SURFACE_WORLD_HEIGHT 256
#define SURFACE_GENERATION_MIN_Y 0
#define SURFACE_GENERATION_MAX_Y_EXCLUSIVE SURFACE_WORLD_HEIGHT
#define SURFACE_GENERATION_SECTION_COUNT \
    (SURFACE_WORLD_HEIGHT / SURFACE_SECTION_HEIGHT)
// WORLD_HEIGHT is the legacy generation height for older call sites. It is
// not the minimum/maximum coordinate contract for sparse Surface sections.
#define WORLD_HEIGHT SURFACE_WORLD_HEIGHT
#define MIN_RENDER_DISTANCE_CHUNKS 2
#define DEFAULT_RENDER_DISTANCE_CHUNKS 10
#define MAX_RENDER_DISTANCE_CHUNKS 12
#define MAX_ACTIVE_CHUNKS ((MAX_RENDER_DISTANCE_CHUNKS * 2 + 1) * (MAX_RENDER_DISTANCE_CHUNKS * 2 + 1))
#define CHUNK_GEN_SUBMISSIONS_PER_FRAME 32
#define MAX_CHUNK_GEN_JOBS 64
#define MAX_CHUNK_FLORA_STRUCTURES 32
#define MAX_MESH_REBUILDS_PER_FRAME 10
#define INITIAL_BLOCK_EDIT_CAPACITY 1024
#define BLOCK_SIZE 1.0f
#define HOTBAR_SIZE 10
#define ATLAS_TILE_SIZE 16
#define ATLAS_TILE_PADDING 8
#define ATLAS_CELL_SIZE (ATLAS_TILE_SIZE + ATLAS_TILE_PADDING * 2)
#define ATLAS_COLUMNS 32
#define ATLAS_ROWS ((TEX_COUNT + ATLAS_COLUMNS - 1) / ATLAS_COLUMNS)
#define COLOR_BLOCK_COUNT 256
#define IMPORT_MIN_BLOCKS 16
#define IMPORT_DEFAULT_BLOCKS 64
#define IMPORT_MAX_BLOCKS 256
#define IMPORT_MAX_FILE_BYTES (64 * 1024 * 1024)
#define IMPORT_MAX_SOURCE_DIMENSION 8192
#define IMPORT_MAX_SOURCE_PIXELS 33554432u
#define IMPORT_MAX_TARGET_PIXELS 65536u
#define IMPORT_MAX_BLOCK_OPERATIONS \
    (64u * 64u * (unsigned int)SURFACE_WORLD_HEIGHT * 2u)
#define IMPORT_PRECISION_STEP 16
#define IMPORT_PRECISION_BIG_STEP 64
#define SAVE_FILE "voxelcraft_save.txt"
#define AUTO_SAVE_INTERVAL_SECONDS 60.0f
#define WATER_VOLUME_CAPACITY 255u
#define DAY_LENGTH_SECONDS 240.0f
#define DEFAULT_WORLD_SEED 0x564f5843u
#define SUN_DISTANCE 420.0f
#define PLAYER_HEIGHT 1.75f
#define PLAYER_RADIUS 0.28f
#define PLAYER_LANDING_SEARCH_DEPTH 32
#define EYE_HEIGHT 1.55f
#define GRAVITY 20.0f
#define JUMP_SPEED 7.0f
#define WALK_SPEED 5.0f
#define SPRINT_SPEED 8.0f
#define FLOAT_VERTICAL_SPEED 5.5f
#define MOUSE_SENSITIVITY 0.0022f
#define REACH_DISTANCE 6.0f
#define CAMERA_MIN_FOV 70.0f
#define CAMERA_MAX_FOV 90.0f
#define CAMERA_FOV_MIN_HEIGHT 4.0f
#define CAMERA_FOV_MAX_HEIGHT 28.0f
#define CAMERA_FOV_SMOOTHING 8.0f
#define CAMERA_MAX_EXTRA_DISTANCE_CHUNKS 2
#define CAMERA_NEAR_CULL_DISTANCE 0.1f

#define SPACE_LAYER_Y (SURFACE_WORLD_HEIGHT + 64)
#define SPACE_LAYER_HEIGHT 128
#define SPACE_LAYER_TOP (SPACE_LAYER_Y + SPACE_LAYER_HEIGHT)
#define SPACE_ENTER_Y ((float)SPACE_LAYER_Y + 24.0f)
#define SPACE_EXIT_Y ((float)SURFACE_WORLD_HEIGHT + 48.0f)
#define SPACE_RENDER_DISTANCE_CHUNKS 4

#define NETHER_LAYER_Y (-64)
#define NETHER_LAYER_TOP (-32)
#define NETHER_HEIGHT (NETHER_LAYER_TOP - NETHER_LAYER_Y)
#define NETHER_RENDER_DISTANCE_CHUNKS 4

#define MAX_TORCH_LIGHTS 512
#define TORCH_LIGHT_RADIUS 6.0f
#define TORCH_LIGHT_STRENGTH 0.85f

#endif
